# Generated by Django 3.1.7 on 2021-03-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_auto_20210304_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='size',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
