# Generated by Django 3.1.7 on 2021-03-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pilot', models.CharField(max_length=50, null=True)),
                ('launch_date', models.DateField(null=True)),
                ('training_mission', models.BooleanField(default=False)),
            ],
        ),
    ]