# Generated by Django 3.1.7 on 2021-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='number_of_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(max_length=254),
        ),
    ]
