# Generated by Django 3.1.7 on 2021-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210314_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='species',
            field=models.CharField(choices=[('jedi', 'JEDI'), ('hutt', 'HUTT'), ('wookie', 'WOOKIE'), ('sith', 'SITH')], default='jedi', max_length=20),
        ),
    ]
