# Generated by Django 3.1.7 on 2021-03-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=20)),
                ('has_been_done', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField()),
                ('date_completion', models.DateTimeField()),
                ('deadline_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.URLField()),
                ('todo', models.ManyToManyField(related_name='all_todos', to='todo.Todo')),
            ],
        ),
    ]
