# Generated by Django 3.1.7 on 2021-03-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_species'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='Index',
        ),
    ]
