# Generated by Django 3.1.7 on 2021-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210315_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='index',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
