# Generated by Django 3.1.7 on 2021-03-09 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_auto_20210307_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='film_category', to='film_app.Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='created_in_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film_app.country'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='film_directory', to='film_app.Director'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
