# Generated by Django 3.1.7 on 2021-03-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20210304_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
