# Generated by Django 3.1.7 on 2021-05-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20210305_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.customer'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rental_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehicle'),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='daily_rate',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='vehicle_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehiclesize'),
        ),
        migrations.AlterField(
            model_name='rentalrate',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='real_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehiclesize'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.vehicletype'),
        ),
        migrations.AlterField(
            model_name='vehiclesize',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
