# Generated by Django 3.1.7 on 2021-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(null=True, to='film_app.Category'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(null=True, to='film_app.Director'),
        ),
    ]
