# Generated by Django 3.1.7 on 2021-05-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gif_app', '0002_auto_20210526_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(to='gif_app.Gif'),
        ),
    ]
