# Generated by Django 3.1.7 on 2021-03-01 18:38

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
